### ISSUE TITLE
Integrate gift pallet

### ISSUE THREAD

**Issue by stanly-johnson** [valibre-org/vln-node#104]
The [Gift pallet](https://github.com/paritytech/substrate/pull/8899) that is currently in development aligns very closely with the free pass/coupon design for escrow. We could integrate it once it is part of frame.

**Comment by olanod** [comment]
Sounds great, it's exactly what I had in mind with the _free-pass pallet_, glad to know it wasn't a bad idea and that other people see the need for it ;)

**Comment by stanly-johnson** [comment]
Closing since gift pallet has been discontinued :(

**Comment by olanod** [comment]
Let's see what will be the alternative 🤔
