### ISSUE TITLE
Asset transferring should take into account different ratios

### ISSUE THREAD

**Issue by c410-f3r** [valibre-org/vln-node#33]
The current algorithm expects that every single asset have a 1:1 ratio, for example, 1 USD = 1 USDv but this statement is not true anymore due to newly created assets like VES or COP . Given an hypothetical USD → BTC  transfer, the final balances of each party would be plain wrong.

**Comment by olanod** [comment]
At the moment it should only be possible to transfer USDv which is always 1:1 collateralized with a compatible `Asset::Collateral`. Transferring other assets might not even make sense or would require some extra work that we don't support yet that requires some off-chain actions, e.g. A provider attests having `1_000_000 COP`, making an on-chain transfer of that COP won't make the money magically appear in the other user account but rather requires an action from that provider to make a bank transfer and give proof of the action being completed. These should be tackled in the "chained transactions" project https://github.com/valibre-org/vln-node/projects/2

**Comment by c410-f3r** [comment]
@olanod Thanks for the explanation
