### ISSUE TITLE
Map the custom runtime types necessary for polkadot apps integration

### ISSUE THREAD

**Issue by c410-f3r** [valibre-org/vln-node#41]
Here is the most recent and incomplete list of types:

```json
{
  "Address": "AccountId",
  "Asset": {
    "_enum": {
      "Btc": null,
      "Collateral": "Collateral",
      "Cop": null,
      "Usdv": null,
      "Ves": null
    }
  },
  "Collateral": {
    "_enum": [
      "Usd",
      "Usdc"
    ]
  },
  "CurrencyId": "Asset"
}
```

Basically, it is just a matter of mapping the custom runtime types into the above `json` parameters, including the modified `Extra` types.

**Comment by olanod** [comment]
Do you know if it's something that can be generated automatically from the code base and make it part of a CI pipeline? I find it tedious if we have to update the definition every time we change the runtime types.

**Comment by c410-f3r** [comment]
Maybe it is possible to scan the metadata to automatically create these `apps` types but I am not aware of any tools that do this or something similar

**Comment by olanod** [comment]
Ok perhaps some day in the future, in the meantime let's do it manually ... Will add this to the kanban board.

**Comment by olanod** [comment]
There's now a mention in the readme with the JSON file in the root of the repo
