### ISSUE TITLE
Destination can be off-chain

### ISSUE THREAD

**Issue by olanod** [valibre-org/vln-node#43]
A transfer destination will not always be an account within the blockchain, it can for example be a bank account or an account in a different blockchain that a liquidity provider controls and has notified the VLN of its existence.

This means `to` parameter of the `Transfer` call should change from an AccountId to an enum type that allows other types of off-chain destinations.
e.g.
```rust
enum Destination {
    Vln(AccountId),
    Bank(DetailsId),
    Btc(BtcId),
    // ...
}
```

**Comment by stanly-johnson** [comment]
@olanod This has been removed in the migration to v3. Is this no longer needed or should I work on integrating this back?

**Comment by olanod** [comment]
Hi Stan, it's still up for discussion but I didn't add it back since the new [Multiaddress](https://github.com/paritytech/substrate/pull/7380) format might be just enough for representing external addresses and identifiers
