### ISSUE TITLE
Cumulus migration

### ISSUE THREAD

**Issue by olanod** [valibre-org/vln-node#49]
Adapting our chain to use [cumulus](https://github.com/paritytech/cumulus) allow us to connect to Rococo v1, the relay-chain testnet for parachain integration.
  
For more info check: https://substrate.dev/cumulus-workshop

Subtasks:
- [ ] _TODO_

**Comment by c410-f3r** [comment]
claim

**Comment by olanod** [comment]
As suggestion from the builder's program it would be better to keep Cumulus integration behind a feature flag so we can compile a parachain ready version of our node while keep using the PoA chain
