### ISSUE TITLE
Add proxy pallet

### ISSUE THREAD

**Issue by olanod** [valibre-org/vln-node#51]
Adding support for proxy accounts will simplify the way Valiu as a liquidity provider manages the accounts of its users.
This is important for organizations joining as liquidity providers since they have more complex needs on how funds should be handled.

**Comment by stanly-johnson** [comment]
Hi @olanod, i can work on this. Is the task to integrate the [proxy pallet](https://github.com/paritytech/substrate/tree/master/frame/proxy) or to create a custom proxy pallet for our needs?

**Comment by olanod** [comment]
Feel free to take it :) it is about integrating the existing proxy pallet
