### ISSUE TITLE
Migrate to FRAMEv2(pallet macro) spliting liquidity pallet

### ISSUE THREAD

**Issue by olanod** [valibre-org/vln-node#55]
Liquidity pallet has all the custom logic of our runtime and does a bunch of things. I propose splitting it in 3 for the time being and in the process migrate to use the new procedural macro `pallet`.
 
- [x] **Backed Asset pallet**: Instantiable pallet used for minting our USDv. A backed asset is collateralized by other assets and transfering it transfers the underling collateral as well.
- [x] **Foreign Asset pallet**:  Allows trusted members attest their ownership of crypto or fiat assets off chain. Those assets could be used as collateral of a backed asset for example.
- [ ] **Swaps pallet** How assets get traded based on the reported liquidity of LPs. Finds matching LPs that can trade a given pair or chains multiple swaps.

**Comment by olanod** [comment]
As initial work I'm cleaning first, removing unused functionality, temporarily removing liquidity pallet and migrating to substrate v3 that adds the stable support for the macro `pallet` as well as an updated `assets` pallet that comes with useful functionality that fits our needs over what provided by orml tokens.

**Comment by shamb0** [comment]
Hello @olanod,

If its open, like to give a try.

Recently worked on similar kind on task on substrate pallets, like to share the PR for reference.

* [pallet-collective | port to frame v2 by shamb0 · Pull Request #8151 · paritytech/substrate](https://github.com/paritytech/substrate/pull/8151)

* [pallet-bounties | Sub-bounties Extn | Design Discussion Notes | quick proto by shamb0 · Pull Request #7965 · paritytech/substrate](https://github.com/paritytech/substrate/pull/7965)

* [Issue 7143 | Refactor Treasury Pallet into Bounties, Tips, and Proposals by shamb0 · Pull Request #7536 · paritytech/substrate](https://github.com/paritytech/substrate/pull/7536)
