### ISSUE TITLE
Create chainspec json

### ISSUE THREAD

**Issue by stanly-johnson** [valibre-org/vln-node#66]
We are currently using the non standard format for chainspec, the common practice is to have json files for each network spec (except local) this way other nodes can connect to the network. This is not a priority now, but we will need it later when we expect other external nodes will connect to VLN.

Reference : https://substrate.dev/docs/en/tutorials/start-a-private-network/customspec
[Polkadot Example](https://github.com/paritytech/polkadot/tree/master/node/service/res)
[Kilt Example](https://github.com/KILTprotocol/mashnet-node/tree/develop/nodes/standalone/res)

**Comment by stanly-johnson** [comment]
> other nodes that can be external to our infrastructure pass the same chainspec name as command line flag they will be able to connect to our chain.

I'm not sure about that, they need to know one of our nodes to set as bootnode right? Ideally chainspec.json would have this info. But you're right its purely for convenience not a necessity.

**Comment by olanod** [comment]
Eventually we can include one or more well-known bootnodes in the code or just mention in the readme or somewhere what is the multi address of Valiu's public full nodes in case people want to use our nodes as bootnodes. e.g. the testnet full-node is reachable publicly in `/dns/vln.valiu.dev/tcp/30333/...` which is what the validators pass as command line argument to bootstrap their connection.
