### ISSUE TITLE
Allow rate providers to update fixed rates

### ISSUE THREAD

**Issue by stanly-johnson** [valibre-org/vln-node#97]
Current implementation of the rate provider pallet expects the providers to upload rate premium and not the actual rate, we could support both `fixed_rate` and `rate_premium` and let the provider choose the format.

Current:
```rust
pub struct RateDetail {
    pub rate: Permill,
}
```

Change to:
```rust
pub enum RateFormat {
 Fixed(FixedU128),
 Premium(Permill)
}

pub struct RateDetail {
    pub rate: RateFormat,
}
```

**Comment by olanod** [comment]
Do you foresee the different kinds of rates sharing any data? otherwise seems a bit redundant to have the enum wrapped in a struct, `RateDetail` could just be the enum where each variant holds its unique data.
